// Generated by CoffeeScript 2.6.1
(function() {
  var asyncFunc, timer;

  timer = function(value, delay) {
    return new Promise(function(resolve, reject) {
      return setTimeout((function() {
        resolve(value);
      }), delay);
    });
  };

  asyncFunc = async function() {
    console.log((await timer(1, 0)));
    console.log((await timer(2, 100)));
    return console.log((await timer(3, 1000)));
  };

  asyncFunc();

}).call(this);
